### ISSUE TITLE
https://github.com/chrisgoringe/cg-custom-core.git cg_custom_core

### ISSUE THREAD

**Issue by cardenluo** [chrisgoringe/cg-custom-core#1]
Not found

**Comment by chrisgoringe** [comment]
Not sure what you mean?

**Comment by cardenluo** [comment]
Skip F:\StableDiffusion\UUUbackup\ComfyUI-ainewsto\comfyui\custom_nodes\.git module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
ASTERR config loaded successfully
Traceback (most recent call last):
  File "F:\StableDiffusion\UUUbackup\ComfyUI-ainewsto\comfyui\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\StableDiffusion\UUUbackup\ComfyUI-ainewsto\comfyui\custom_nodes\cg-noise-main\__init__.py", line 2, in <module>
    from .hijack import NODE_CLASS_MAPPINGS as hijack_mappings
  File "F:\StableDiffusion\UUUbackup\ComfyUI-ainewsto\comfyui\custom_nodes\cg-noise-main\hijack.py", line 2, in <module>    from custom_nodes.cg_custom_core.ui_decorator import ui_signal
ModuleNotFoundError: No module named 'custom_nodes.cg_custom_core'

Cannot import F:\StableDiffusion\UUUbackup\ComfyUI-ainewsto\comfyui\custom_nodes\cg-noise-main module for custom nodes: No module named 'custom_nodes.cg_custom_core'
Comfyroll Custom Nodes: Loaded
F:\StableDiffusion\UUUbackup\ComfyUI-ainewsto\comfyui\python\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[tinyterraNodes] Loaded

**Comment by cardenluo** [comment]
sorry , I thought there was something wrong with the installation path. I tried many times and finally succeeded, probably due to network issues.
